root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  gameplay/mechanics: gameplay/mechanics.md
  whitepaper/tokenomics: whitepaper/tokenomics.md
  roadmap/milestones: roadmap/milestones.md

# GitBook configuration
title: RoyaleLabs Documentation
description: Official documentation for Project Royale
author: RoyaleLabs Team

# Sync settings
sync:
  git:
    enabled: true
    default_branch: main
    sync_on_push: true 